import os
import numpy as np

def generate_samples(file_path, output_folder, num_sampled_points, num_samples, delimiter=','):
    """
    Loads an input .xyz point cloud file (comma-separated by default) and creates several
    sampled point clouds. Each sample is generated by randomly selecting 'num_sampled_points'
    from the original point cloud (without replacement if possible, otherwise with replacement).
    
    Parameters:
      file_path: Path to the input .xyz file.
      output_folder: Folder where the sampled point clouds will be saved.
      num_sampled_points: Number of points per sampled point cloud.
      num_samples: Number of different samples to generate.
      delimiter: Delimiter used in the .xyz file.
    """
    try:
        data = np.loadtxt(file_path, delimiter=delimiter)
    except Exception as e:
        print("Error reading the file:", e)
        return
    
    if data.ndim != 2 or data.shape[1] < 3:
        print("The file does not contain valid 3D point cloud data.")
        return
    
    total_points = data.shape[0]
    print(f"Loaded point cloud with {total_points} points.")
    
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    
    # Use the base name of the file (without extension) for output naming.
    base_name = os.path.splitext(os.path.basename(file_path))[0]
    
    for i in range(1, num_samples+1):
        # If there are enough points, sample without replacement.
        if total_points >= num_sampled_points:
            indices = np.random.choice(total_points, num_sampled_points, replace=False)
        else:
            print("Warning: Not enough points in the input; sampling with replacement.")
            indices = np.random.choice(total_points, num_sampled_points, replace=True)
        
        sample_points = data[indices]
        output_file = os.path.join(output_folder, f"{base_name}_sample_{i}.npy")
        np.save(output_file, sample_points)
        print(f"Saved sample {i} to {output_file}")

def main():
    # ============================
    # === Configuration Values ===
    # ============================
    
    # Path to the input .xyz point cloud file.
    FILE_PATH = r"C:\Dokumente\Studium\6. Semester\Bachelorarbeit\Code\Scan\transformed_meshes\transformed_point_cloud.xyz"
    
    # Folder where the sampled point clouds will be saved.
    OUTPUT_FOLDER = r"C:\Dokumente\Studium\6. Semester\Bachelorarbeit\Code\presampled_meshes\32_points_from_point_cloud"
    
    # Number of points to sample per point cloud.
    NUM_SAMPLED_POINTS = 32
    
    # Number of different samples to create.
    NUM_SAMPLES = 10
    
    # Delimiter used in the .xyz file. Adjust if needed (e.g., ' ' for whitespace).
    DELIMITER = ','
    
    generate_samples(FILE_PATH, OUTPUT_FOLDER, NUM_SAMPLED_POINTS, NUM_SAMPLES, delimiter=DELIMITER)

if __name__ == '__main__':
    main()
